/*
* geocell=# \d geocell_band
                                   Table "public.geocell_band"
    Column     |         Type          | Collation | Nullable |             Default
---------------+-----------------------+-----------+----------+----------------------------------
 id            | bigint                |           | not null | generated by default as identity
 band          | character varying(50) |           |          |
 bandwidth     | double precision      |           |          |
 uplink_freq   | double precision      |           |          |
 downlink_freq | double precision      |           |          |
 earfcn        | double precision      |           |          |
Indexes:
    "geocell_band_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "geocell_cell" CONSTRAINT "geocell_cell_band_id_be01fd35_fk_geocell_band_id" FOREIGN KEY (band_id) REFERENCES geocell_band(id) DEFERRABLE INITIALLY DEFERRED

* */
package main.kotlin.oicnanev.org.geocell.domain.entities

data class Band(
    val id: Int?,
    val band: String?,
    val bandwidth: Double?,
    val uplinkFreq: Double?,
    val downlinkFreq: Double?,
    val earfcn: Double?
)
