/*
geocell-# \d geocell_cellpolygon
                                 Table "public.geocell_cellpolygon"
    Column     |           Type           | Collation | Nullable |             Default
---------------+--------------------------+-----------+----------+----------------------------------
 id            | bigint                   |           | not null | generated by default as identity
 polygon       | geography(PolygonZ,4326) |           |          |
 cell_id       | bigint                   |           |          |
 polygon_short | geography(PolygonZ,4326) |           |          |
Indexes:
    "geocell_cellpolygon_pkey" PRIMARY KEY, btree (id)
    "geocell_cellpolygon_cell_id_853b8f8a" btree (cell_id)
    "geocell_cellpolygon_polygon_c2d09343_id" gist (polygon)
    "geocell_cellpolygon_polygon_short_e1b1f087_id" gist (polygon_short)
Foreign-key constraints:
    "geocell_cellpolygon_cell_id_853b8f8a_fk_geocell_cell_id" FOREIGN KEY (cell_id) REFERENCES geocell_cell(id) DEFERRABLE INITIALLY DEFERRED

*/
package main.kotlin.oicnanev.org.geocell.domain.entities

import java.awt.Polygon

data class CellPolygon(
    val id: Long?,
    val polygon: PolygonZ,  // don't know if 4326 is missing
    val cellId: Long,
    val polygonShort: Polygon
)

data class PolygonZ(
    val x: Double,
    val y: Double,
    val z: Double
)
