/*
geocell=# \d geocell_cell
                                  Table "public.geocell_cell"
   Column    |          Type          | Collation | Nullable |             Default
-------------+------------------------+-----------+----------+----------------------------------
 id          | bigint                 |           | not null | generated by default as identity
 lac_tac     | character varying(50)  |           | not null |
 ci          | character varying(20)  |           |          |
 eci_nci     | character varying(20)  |           |          |
 cgi         | character varying(30)  |           |          |
 paragon_cgi | character varying(100) |           |          |
 technology  | integer                |           | not null |
 direction   | integer                |           |          |
 name        | character varying(200) |           |          |
 created     | date                   |           | not null |
 modified    | date                   |           | not null |
 band_id     | bigint                 |           |          |
 enb_gnb_id  | bigint                 |           |          |
 location_id | bigint                 |           |          |
 mcc_mnc_id  | bigint                 |           |          |
 modifier_id | integer                |           |          |
 owner_id    | integer                |           |          |
Indexes:
    "geocell_cell_pkey" PRIMARY KEY, btree (id)
    "geocell_cell_band_id_be01fd35" btree (band_id)
    "geocell_cell_enb_gnb_id_f28334a6" btree (enb_gnb_id)
    "geocell_cell_location_id_691e8db3" btree (location_id)
    "geocell_cell_mcc_mnc_id_c2b9e752" btree (mcc_mnc_id)
    "geocell_cell_modifier_id_9bbe495f" btree (modifier_id)
    "geocell_cell_owner_id_4861ee1b" btree (owner_id)
Foreign-key constraints:
    "geocell_cell_band_id_be01fd35_fk_geocell_band_id" FOREIGN KEY (band_id) REFERENCES geocell_band(id) DEFERRABLE INITIALLY DEFERRED
    "geocell_cell_enb_gnb_id_f28334a6_fk_geocell_enbgnb_id" FOREIGN KEY (enb_gnb_id) REFERENCES geocell_enbgnb(id) DEFERRABLE INITIALLY DEFERRED
    "geocell_cell_location_id_691e8db3_fk_geocell_location_id" FOREIGN KEY (location_id) REFERENCES geocell_location(id) DEFERRABLE INITIALLY DEFERRED
    "geocell_cell_mcc_mnc_id_c2b9e752_fk_geocell_mccmnc_id" FOREIGN KEY (mcc_mnc_id) REFERENCES geocell_mccmnc(id) DEFERRABLE INITIALLY DEFERRED
    "geocell_cell_modifier_id_9bbe495f_fk_auth_user_id" FOREIGN KEY (modifier_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    "geocell_cell_owner_id_4861ee1b_fk_auth_user_id" FOREIGN KEY (owner_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "geocell_cellpolygon" CONSTRAINT "geocell_cellpolygon_cell_id_853b8f8a_fk_geocell_cell_id" FOREIGN KEY (cell_id) REFERENCES geocell_cell(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "geocell_coverage" CONSTRAINT "geocell_coverage_cell_id_eb7e8cbf_fk_geocell_cell_id" FOREIGN KEY (cell_id) REFERENCES geocell_cell(id) DEFERRABLE INITIALLY DEFERRED
*/
package main.kotlin.oicnanev.org.geocell.domain.entities

import java.lang.reflect.Modifier
import java.sql.Date

data class Cell(
    val id: Long?,
    val lacTac: String,
    val ci: String?,
    val eciNci: String?,
    val cgi: String?,
    val paragon_cgi: String?,
    val technology: Int,
    val direction: Int?,
    val name: String?,
    val created: Date,
    val updated: Date,
    val bandId: Int?,
    val enbGnbId: Int?,
    val locationId: Int?,
    val mccMncId: Int?,
    val modifierId: Int?,
    val ownerId: Int?
)
