/*
geocell-# \d geocell_county
                                 Table "public.geocell_county"
   Column    |          Type          | Collation | Nullable |             Default
-------------+------------------------+-----------+----------+----------------------------------
 id          | bigint                 |           | not null | generated by default as identity
 id_county   | character varying(20)  |           | not null |
 county      | character varying(100) |           | not null |
 polygon     | geometry(Polygon,4326) |           |          |
 district_id | character varying(20)  |           |          |
Indexes:
    "geocell_county_pkey" PRIMARY KEY, btree (id)
    "geocell_county_district_id_51ce031e" btree (district_id)
    "geocell_county_district_id_51ce031e_like" btree (district_id varchar_pattern_ops)
    "geocell_county_district_id_id_ed5fb1a1_uniq" UNIQUE CONSTRAINT, btree (district_id, id)
    "geocell_county_polygon_367f40df_id" gist (polygon)
Foreign-key constraints:
    "geocell_county_district_id_51ce031e_fk_geocell_district_id" FOREIGN KEY (district_id) REFERENCES geocell_district(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "geocell_location" CONSTRAINT "geocell_location_id_county_id_f78e6959_fk_geocell_county_id" FOREIGN KEY (id_county_id) REFERENCES geocell_county(id) DEFERRABLE INITIALLY DEFERRED
 */
package main.kotlin.oicnanev.org.geocell.domain.entities

data class County(
    val id: Long?,
    val id_county: String,
    val county: String,
    val polygon: PolygonZ?,
    val district_id: String?
)
