/*
geocell-# \d geocell_coverage
                                   Table "public.geocell_coverage"
     Column      |           Type           | Collation | Nullable |             Default
-----------------+--------------------------+-----------+----------+----------------------------------
 id              | bigint                   |           | not null | generated by default as identity
 signal_strength | integer                  |           |          |
 timestamp       | timestamp with time zone |           | not null |
 cell_id         | bigint                   |           | not null |
 location_id     | bigint                   |           | not null |
 user_id         | integer                  |           |          |
Indexes:
    "geocell_coverage_pkey" PRIMARY KEY, btree (id)
    "geocell_coverage_cell_id_eb7e8cbf" btree (cell_id)
    "geocell_coverage_location_id_08252657" btree (location_id)
    "geocell_coverage_user_id_6e1de71b" btree (user_id)
Foreign-key constraints:
    "geocell_coverage_cell_id_eb7e8cbf_fk_geocell_cell_id" FOREIGN KEY (cell_id) REFERENCES geocell_cell(id) DEFERRABLE INITIALLY DEFERRED
    "geocell_coverage_location_id_08252657_fk_geocell_location_id" FOREIGN KEY (location_id) REFERENCES geocell_location(id) DEFERRABLE INITIALLY DEFERRED
    "geocell_coverage_user_id_6e1de71b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED

 */
package main.kotlin.oicnanev.org.geocell.domain.entities

import java.sql.Timestamp

data class Coverage(
    val id: Long?,
    val signalStrength: Int?,
    val timestamp: Timestamp,
    val cellId: Long,
    val locationId: Long,
    val userId: Int?
)
