/*
geocell-# \d geocell_location
                                    Table "public.geocell_location"
       Column       |          Type          | Collation | Nullable |             Default
--------------------+------------------------+-----------+----------+----------------------------------
 id                 | bigint                 |           | not null | generated by default as identity
 coordinates        | geometry(Point,4326)   |           |          |
 address            | character varying(100) |           |          |
 address1           | character varying(100) |           |          |
 zip4               | integer                |           | not null |
 zip3               | integer                |           | not null |
 postal_designation | character varying(100) |           |          |
 id_county_id       | bigint                 |           |          |
Indexes:
    "geocell_location_pkey" PRIMARY KEY, btree (id)
    "geocell_location_coordinates_0af5b426_id" gist (coordinates)
    "geocell_location_id_county_id_f78e6959" btree (id_county_id)
Foreign-key constraints:
    "geocell_location_id_county_id_f78e6959_fk_geocell_county_id" FOREIGN KEY (id_county_id) REFERENCES geocell_county(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "geocell_cell" CONSTRAINT "geocell_cell_location_id_691e8db3_fk_geocell_location_id" FOREIGN KEY (location_id) REFERENCES geocell_location(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "geocell_coverage" CONSTRAINT "geocell_coverage_location_id_08252657_fk_geocell_location_id" FOREIGN KEY (location_id) REFERENCES geocell_location(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "geocell_enbgnb" CONSTRAINT "geocell_enbgnb_location_id_8c4f5999_fk_geocell_location_id" FOREIGN KEY (location_id) REFERENCES geocell_location(id) DEFERRABLE INITIALLY DEFERRED

 */
package main.kotlin.oicnanev.org.geocell.domain.entities

data class Location(
    val id: Long?,
    val coodinates: Point?,
    val address: String?,
    val address1: String?,
    val zip4: Int,
    val zip3: Int,
    val postalDesignation: String?,
    val idCountyId: Long?
)

data class Point(
    val x: Double,
    val y: Double
)
