/*
geocell-# \d geocell_mccmnc
                                 Table "public.geocell_mccmnc"
   Column   |          Type          | Collation | Nullable |             Default
------------+------------------------+-----------+----------+----------------------------------
 id         | bigint                 |           | not null | generated by default as identity
 type       | character varying(100) |           |          |
 mcc        | integer                |           | not null |
 mnc        | integer                |           | not null |
 brand      | character varying(100) |           |          |
 operator   | character varying(200) |           |          |
 status     | character varying(100) |           |          |
 bands      | character varying(200) |           |          |
 notes      | character varying(300) |           |          |
 country_id | character varying(100) |           |          |
Indexes:
    "geocell_mccmnc_pkey" PRIMARY KEY, btree (id)
    "geocell_mccmnc_country_id_8fe6cc8c" btree (country_id)
    "geocell_mccmnc_country_id_8fe6cc8c_like" btree (country_id varchar_pattern_ops)
    "geocell_mccmnc_mcc_mnc_47daf33b_uniq" UNIQUE CONSTRAINT, btree (mcc, mnc)
Foreign-key constraints:
    "geocell_mccmnc_country_id_8fe6cc8c_fk_geocell_country_name" FOREIGN KEY (country_id) REFERENCES geocell_country(name) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "geocell_cell" CONSTRAINT "geocell_cell_mcc_mnc_id_c2b9e752_fk_geocell_mccmnc_id" FOREIGN KEY (mcc_mnc_id) REFERENCES geocell_mccmnc(id) DEFERRABLE INITIALLY DEFERRED
 */
package main.kotlin.oicnanev.org.geocell.domain.entities

data class MccMnc(
    val id: Long?,
    val type: String?,
    val mcc: Int,
    val mnc: Int,
    val brand: String?,
    val operator: String?,
    val status: String?,
    val bands: String?,
    val notes: String?,
    val countryId: String?
)
